# Generated by Django 5.1 on 2024-09-02 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('funds', '0001_initial'),
        ('loans', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.customer'),
        ),
        migrations.AddField(
            model_name='loanpayment',
            name='loan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loans.loan'),
        ),
        migrations.AddField(
            model_name='loanpayment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.customer'),
        ),
        migrations.AddField(
            model_name='loanplan',
            name='loan_fund',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funds.baseloanfund'),
        ),
        migrations.AddField(
            model_name='loan',
            name='loan_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loans.loanplan'),
        ),
        migrations.AddField(
            model_name='loanrequest',
            name='loan_officer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.bankpersonnel'),
        ),
        migrations.AddField(
            model_name='loanrequest',
            name='loan_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loans.loanplan'),
        ),
        migrations.AddField(
            model_name='loanrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.customer'),
        ),
    ]
