# Generated by Django 5.1 on 2024-09-02 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseLoanFund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('BIG', 'Big Loans Fund'), ('MEDIUM', 'Medium Loans Fund'), ('SMALL', 'Small Loans Fund')], max_length=10, unique=True)),
                ('start_fund', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('current_value', models.FloatField()),
            ],
        ),
    ]
